# Generated by Django 4.0.6 on 2022-08-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMat', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nomMed', models.CharField(max_length=100)),
                ('aPat', models.CharField(max_length=100)),
                ('aMat', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaConsulta', models.DateField()),
                ('nombrePaci', models.CharField(max_length=100)),
                ('apPatPaci', models.CharField(max_length=100)),
                ('apMatPaci', models.CharField(max_length=100)),
                ('edadPaci', models.IntegerField()),
                ('sexoPaci', models.CharField(max_length=100)),
                ('tipoPaci', models.CharField(max_length=100)),
                ('motivoCons', models.CharField(max_length=100)),
                ('solucion', models.CharField(max_length=100)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicosApp.medico')),
            ],
        ),
        migrations.CreateModel(
            name='conferencia',
            fields=[
                ('id_conferencia', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicosApp.medico')),
            ],
        ),
    ]
