# Generated by Django 4.0.6 on 2022-08-03 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='horario',
        ),
        migrations.AddField(
            model_name='conferencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fechaConsulta',
            field=models.DateTimeField(),
        ),
    ]
