# Generated by Django 4.0.6 on 2022-08-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicosApp', '0002_remove_conferencia_horario_conferencia_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='id_medico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='id_medico',
        ),
    ]
