# Generated by Django 4.0.6 on 2022-08-10 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicosApp', '0003_remove_conferencia_id_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fechaConsulta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
