# Generated by Django 4.0.6 on 2022-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicosApp', '0004_alter_consulta_fechaconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivoCons',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='solucion',
            field=models.CharField(max_length=500),
        ),
    ]
